version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      MSSQL_SA_PASSWORD: "Vrysmplpswd1!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - sqlserver
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=Kinopoisk;User=sa;Password=Vrysmplpswd1!;"
    ports:
      - "8080:80"
        